##please provide the summary_stats prefix for each GWAS, the absolute paths to the summary stats and the top loci files
##and the effective sample size (Neff)

summary_stats_prefix:
  - daner_mya_meta_cc_20.mar23
top_loci_file:
  - /projects/0/pgcd0522/finemapping/SAFFARI/resources/daner_mya_meta_cc_20.mar23_loci_ranges.tsv
full_sumstats:
  - /projects/0/pgcd0522/finemapping/SAFFARI/resources/daner_mya_meta_cc_20.mar23.gz

N:
 - 9867.10
